# Generated by Django 5.2.4 on 2025-07-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='currency',
            field=models.CharField(choices=[('NGN', 'Nigerian Naira (NGN)'), ('USD', 'US Dollar (USD)'), ('EUR', 'Euro (EUR)'), ('GBP', 'British Pound (GBP)'), ('CAD', 'Canadian Dollar (CAD)'), ('AUD', 'Australian Dollar (AUD)'), ('JPY', 'Japanese Yen (JPY)'), ('ZAR', 'South African Rand (ZAR)')], default='NGN', max_length=3),
        ),
    ]
